// This file has been autogenerated from a class added in the UI designer.

using System;
using CryptoEngine.AES;
using Foundation;
using AppKit;

namespace NeuralCrypto.KeyGen
{
	public partial class AESKeyGen : NSViewController
	{
		public AESKeyGen (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidDisappear()
        {
            base.ViewDidDisappear();
            Console.WriteLine("lol");
        }

        partial void KeySizeButton(NSObject sender)
        {
            int size = 0;
            switch ((int)KeySizeOutlet.IndexOfSelectedItem)
            {
                case 0:
                    size = 128; break;
                case 1:
                    size = 192; break;
                case 2:
                    size = 256; break;
                default:
                    throw new Exception("Invalid Value");
            }

            var keys = AES.DefineKeys(size);

            EntryBloc.StringValue = "Bloc d'entrée : " + Convert.ToBase64String(keys[0]);
            IV.StringValue = "Vecteur d'initialisation : " + Convert.ToBase64String(keys[1]);
        }
    }
}
