// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace NeuralCrypto.KeyGen
{
	public partial class KeyGenController : NSViewController
	{
		public KeyGenController (IntPtr handle) : base (handle)
		{
		}

        partial void CreateSymetricKey(NSObject sender)
        {
            this.View.Window.Close();

            var storyboard = NSStoryboard.FromName("KeyGenStoryboard", null);
            var controller = storyboard.InstantiateControllerWithIdentifier("AESWindow") as NSWindowController;
            controller.ShowWindow(this);
        }
    }
}
