// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using AppKit;

namespace NeuralCrypto.Main
{
	public partial class MainViewController : NSViewController
	{
		public MainViewController (IntPtr handle) : base (handle)
		{
		}

        partial void KeyGenButton(NSObject sender)
        {
            var storyboard = NSStoryboard.FromName("KeyGenStoryboard", null);
            var controller = storyboard.InstantiateControllerWithIdentifier("KeyGenMain") as NSWindowController;
            controller.ShowWindow(this);
        }
    }
}
